apiVersion: v1
kind: Service
metadata:
  name: myhelm-svc
  labels:
    app: {{ .Values.service.label }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      nodePort: {{ .Values.service.nodePort }} 
  selector:
    app: {{ .Values.service.label }}
