apiVersion: v1
kind: Service
metadata:
  name: hpa-service
  labels:
    run: hpa-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    run: hpa-deployment
  type: NodePort
