apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  key1: value1
  key2: "cos tam jako value 2"
  key3: |
    to jest
    multi line string
    trzecia linia tutaj
    i ostatnia
    tez
  config.json: |
    {
      "attr1": "value1",
      "attr2": "value2"
      }
