apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ubuntu
  name: ubuntu
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    command: ["sh" , "-c", "while true ; do sleep 1d ; done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
