apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: user-request-devops
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0daR1YyYjNCek1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXp3TEhkVkwwN2thMDVDVkZWSDJiRnk1OTcxYUp3UStySG1EOTk1SzhUVUR3CmRMbjk5RVhHWFVCeFVXZ0dOem9ib3BFZExjeXhGOStidm5xT2M3MGxYazlGK2dQT0RBa3ZCNXVZdEltR0pQU3YKS2tFb1NhWEl5SS9YQjZuMHFqaTdCUDFOUkN1Mko4RmRZdFFxZ0JwV3ZsTXVJK3VoaE1XcFA3K1hnOUk5UUliTQp5Y3IycDU3eDBBbktPcy9nZzViZzVSbm5rWmoxVVNOZGVYQnlGb3ZGVWpwUkQxSmcwa3ptdSt3bEx4aTgxOENDCkZLL0hrR1dhZ211aFhCa0dxbmNiamFJN0ZRR29wRzNtR3dZbmhWZFE0K2dwSVBFckI3WXdVdzNzbk1CMHAxUmIKNWl0Nmp2YjJHRDZIZERzd2FiR0tDZ3BWNWx5UERvcmNVeDAvUkZqT1B3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBRkZQUmpLN0cveXIyRHpJcnNHb3FuR0NXeW5VZ2ZsaWdEcG84c2xhc29wYlRRMDMzamtnCk9nTGxmVmpvWWZNa29pRHVZUE9vV293MGlQNFZzeXNMUm9RaVFEVWpndWtXUkRVdE5lRW9kUXgwV2I1TGp2QzYKeFZaeHZwSHhSMm5aYWF6cmllN1BRQ0RpSytkQWJyS3ZYdlRXbm5IUm9sby9VdjhmakJNVTRicmtFU2I3Q1lieQpuWkluUFMzRGdHUU1qSXFvbnJqaGREMHhnQWMwVCswbG9VeW9SR3lZd0RaSy9ORWVMVm9Zc1dLMktlck1yOFFhCkhLcnN4aXhRcjhPL1R3VDNEdGNWSm5pdVU5UlZ5WUwwdUZKRUphUElET2VjTTZhWkJMbFI4MCt2WTB5OWY2ZVEKS0NMREE0STVtWEZsZDNLSGtMa2JrMXlvT2ZldzV0RzBoejA9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  expirationSeconds: 315569260
  usages:
  - digital signature
  - key encipherment
  - client auth
